# Entity Types Configuration for LightRAG Knowledge Graph Construction
#
# This configuration file defines the entity types that LightRAG will use during
# entity extraction and graph construction. Entity types guide the LLM to extract
# relevant entities based on your knowledge domain.
#
# Structure:
#   entity_types:
#     - type_name: <lowercase_no_spaces>
#       description: "<human-readable description>"
#       examples:
#         - "<example 1>"
#         - "<example 2>"
#
# Customization:
# - Add domain-specific entity types using POST /api/v1/config/entity-types
# - Or edit this file directly and restart the service
# - See docs/entity-configuration.md for domain-specific examples

entity_types:
  - type_name: person
    description: "Individual names, contact information, professionals mentioned in CVs"
    examples:
      - "John Doe"
      - "Dr. Jane Smith"
      - "CEO Bob Johnson"
      - "Professor Alice Williams"
      - "Software Engineer Maria Garcia"
      - "Michael Johnson, PhD"

  - type_name: company
    description: "Organizations, employers, companies, institutions, universities"
    examples:
      - "Google LLC"
      - "Microsoft Corporation"
      - "Stanford University"
      - "Amazon Web Services"
      - "Meta Platforms Inc."
      - "Acme Inc."

  - type_name: domain
    description: "Professional fields, industry sectors, knowledge areas that connect jobs, skills, and technologies"
    examples:
      - "Data Science"
      - "Cloud Computing"
      - "Artificial Intelligence"
      - "Cybersecurity"
      - "DevOps"
      - "Database Administration"

  - type_name: product
    description: "Software products, platforms, tools, and commercial offerings"
    examples:
      - "PostgreSQL"
      - "Microsoft Azure"
      - "Adobe Photoshop"
      - "Salesforce"
      - "AWS Lambda"
      - "Oracle Database"

  - type_name: location
    description: "Cities, countries, addresses, geographic locations"
    examples:
      - "San Francisco, CA"
      - "Building A, Floor 3"
      - "United States"
      - "Silicon Valley"
      - "123 Main Street"
      - "United Kingdom"

  - type_name: technology
    description: "Technologies, frameworks, programming languages, and technical tools"
    examples:
      - "Python"
      - "React.js"
      - "Docker"
      - "Neo4j"
      - "Kubernetes"

  - type_name: event
    description: "Events, meetings, conferences, and significant occurrences"
    examples:
      - "Project Kickoff Meeting"
      - "AWS re:Invent 2025"
      - "Q4 Budget Review"
      - "Product Launch"
      - "Annual Performance Review"

  - type_name: document
    description: "Documents, reports, policies, and written materials"
    examples:
      - "CV"
      - "Employee Handbook"
      - "API Documentation"
      - "Privacy Policy"
      - "Q3 Financial Report"
      - "Technical Specification"

  - type_name: job
    description: "Job titles, roles, positions, occupations"
    examples:
      - "Senior Software Engineer"
      - "Product Manager"
      - "Data Scientist"
      - "Database Administrator"
      - "Chief Technology Officer"
      - "Full Stack Developer"

  - type_name: skill
    description: "Professional skills, competencies, abilities"
    examples:
      - "Python programming"
      - "SQL query optimization"
      - "Project management"
      - "Machine learning"
      - "Team leadership"
      - "Data analysis"
